pipeline {

    agent any

    stages {

        stage('Clone Information') {

            steps {

                echo 'Repository cloned successfully.'

            }

        }

        stage('Display Workspace') {

            steps {

                bat 'cd'
                bat 'dir'

            }

        }

    }

}